apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-git-repo
spec:
  interval: 1m
  url: https://github.com/Avnshrai/podinfo-app.git
  ref:
    branch: main

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-kustomization
spec:
  interval: 1m
  path: "./trivy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-git-repo

